### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by manubb** [sgentile/pixi-overlay-markers#2]
Hello
Each time the layer is redrawn, all marker positions are projected: 
https://github.com/sgentile/pixi-overlay-markers/blob/f3d3f43d0548401ff2969b1953da8b53985c3dc9/src/PixiOverlayMarkers.js#L113

This is an expensive operation that can be done only once (or each time markers positions are updated).

This is unrelated to the previous point but you can trigger a pixi layer redraw with:
```js
pixiLayer._update();
```

**Comment by sgentile** [comment]
I see, that is very helpful - I had thought ever time it scaled it would change, but as you say the lat/long hasn't changed so I don't need to keep calling it 

Thanks, I'll put that in.  Appreciate your feedback!

**Comment by sgentile** [comment]
updated in 1.3.0 to only call project once.   Added a transformation callback function that can be used to project if needed.

added a function update to use the update function of the pixi overlay for redrawing vs. calling render each time
